name: vikrantkelkar
favicon: null
layout_spectrum: 0.12488039233721793
typography_spectrum: 0.9511952621396631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07730807480402291
  lightness: 0.7868594662286341
  saturation: 0.13115224265493453
  rhythmicContrast: 0.7104067641776055
purpose: []
